-- Bunone Bondhon Supabase schema
-- Run this in the Supabase SQL editor after creating the project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  email text not null unique,
  phone_no text,
  user_address text,
  role text not null default 'customer' check (role in ('customer', 'admin')),
  language_preference text not null default 'en',
  theme_preference text not null default 'light' check (theme_preference in ('light', 'dark')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  product_name text not null,
  slug text generated always as (regexp_replace(lower(product_name), '[^a-z0-9]+', '-', 'g')) stored,
  in_stock integer not null default 0 check (in_stock >= 0),
  price numeric(10,2) not null check (price >= 0),
  description text,
  image_url text,
  type text not null check (type in ('jewellery', 'clothing', 'mufflers', 'other')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  total_price numeric(12,2) not null check (total_price >= 0),
  payment_method text not null check (payment_method in ('cod', 'bkash', 'nagad', 'card', 'other')),
  confirm_payment boolean not null default false,
  order_status text not null default 'paid',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null check (quantity > 0),
  product_price numeric(10,2) not null check (product_price >= 0)
);

create index if not exists idx_products_type on public.products(type);
create index if not exists idx_cart_items_user_id on public.cart_items(user_id);
create index if not exists idx_orders_user_id on public.orders(user_id);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Public products are readable" on public.products for select using (true);

create policy "Users can read their profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can create their profile" on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id);

create policy "Users can manage their cart" on public.cart_items
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can read their orders" on public.orders
for select using (auth.uid() = user_id);

create policy "Users can read their order items" on public.order_items
for select using (
  exists (
    select 1 from public.orders o
    where o.id = order_id and o.user_id = auth.uid()
  )
);

create policy "Admins can manage products" on public.products
for all using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
) with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

insert into public.products (product_name, in_stock, price, description, image_url, type) values
('Gold Necklace', 10, 1500.00, 'Elegant gold necklace for special occasions.', 'https://i.ibb.co.com/wF9b8XZ0/gold-necklace.jpg', 'jewellery'),
('Silver Ring', 25, 1200.00, 'Sterling silver ring with classic design.', 'https://i.ibb.co.com/ZpFBdV0K/silver-ring.jpg', 'jewellery'),
('Cotton T-Shirt', 50, 500.00, 'Comfortable cotton t-shirt available in all sizes.', 'https://i.ibb.co.com/LTKYXp5/cotton-tshirt.jpg', 'clothing'),
('Woolen Scarf', 20, 300.00, 'Soft woolen scarf for winter.', 'https://i.ibb.co.com/q3MHHZgL/woolen-scarf.jpg', 'mufflers'),
('Handmade Bag', 15, 800.00, 'Stylish handmade bag with durable materials.', 'https://i.ibb.co.com/9HKGxrX1/handmade-bag.jpg', 'other'),
('Traditional Saree', 15, 2800.00, 'Handwoven cotton saree with traditional patterns.', 'https://i.ibb.co.com/j9WkwZyK/traditional-saree.jpg', 'clothing'),
('Salwar Kameez', 20, 1800.00, 'Elegant embroidered salwar kameez set with dupatta.', 'https://i.ibb.co.com/1D275BJ/salwar-kameez.jpg', 'clothing'),
('Lehenga Skirt', 10, 4500.00, 'Designer lehenga choli with intricate zari work.', 'https://i.ibb.co.com/G3QdQcVv/lehenga-skirt.jpg', 'clothing'),
('Kurti', 25, 1200.00, 'Trendy kurti perfect for casual and festive wear.', 'https://i.ibb.co.com/9fRLWc8/kurti.jpg', 'clothing')
on conflict do nothing;